name: Mario App CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: mario-game
  EKS_CLUSTER_NAME: mario-eks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::855158726462:role/github-actions-mario-eks-role
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      # 5️⃣ Trivy security scan
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $ECR_REPOSITORY:${{ github.sha }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL

      # 6️⃣ Tag & push image to ECR
      - name: Push image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY

          docker tag $ECR_REPOSITORY:${{ github.sha }} $ECR_URI:${{ github.sha }}
          docker tag $ECR_REPOSITORY:${{ github.sha }} $ECR_URI:latest

          docker push $ECR_URI:${{ github.sha }}
          docker push $ECR_URI:latest

      # 7️⃣ Update kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      # 8️⃣ Deploy to EKS
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/mario \
            mario=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

          kubectl rollout status deployment/mario
